</div>

<footer class="fixed-bottom footer">
    <div class="container text-center">
        <span class="text-muted">Icons made by <a href="https://www.flaticon.com/authors/freepik"
                title="Freepik">Freepik</a>, <a href="https://www.flaticon.com/authors/smashicons"
                title="Smashicons">Smashicons</a> and <a href="https://www.flaticon.com/authors/smashicons"
                title="Smashicons">Smashicons</a> from <a href="https://www.flaticon.com/" title="Flaticon">
                www.flaticon.com</a></span>
                <br>
                <a href='?langue=francais'>Français</a> / <a href='?langue=english'>English</a>
    </div>
</footer>
</body>
</html>